---
host: this.is.mydomain.net
host_port: 3000
redirect: 192.168.1.2
redirect_port: 80
---
host: mydomain.net
host_port: 3000
redirect: 192.168.1.3
redirect_port: 80
---
#and just everywhere
listening_port: 80
scheme: http
domain: * #Leave this like that


